-- CREATE DATABASE
CREATE OR REPLACE DATABASE spotify;

-- CREATE SCHEMA
CREATE OR REPLACE SCHEMA spotify_track;
CREATE OR REPLACE SCHEMA file_formats;
CREATE OR REPLACE SCHEMA external_stages;
CREATE OR REPLACE SCHEMA pipes;

-- CREATE TABLE
CREATE OR REPLACE TABLE SPOTIFY.SPOTIFY_TRACK.album(
    album_id STRING,
    album_name STRING,
    release_date DATE,
    total_track NUMBER,
    url STRING);

CREATE OR REPLACE TABLE SPOTIFY.SPOTIFY_TRACK.artist(
    artist_id STRING,
    artist_name STRING,
    external_url STRING);

CREATE OR REPLACE TABLE SPOTIFY.SPOTIFY_TRACK.song(
    song_id STRING,
    song_name STRING,
    duration_ms NUMBER,
    url STRING,
    popularity NUMBER,
    song_added DATETIME,
    album_id STRING,
    artist_id STRING);SPOTIFY.SPOTIFY_TRACK.ARTIST

-- CREATE FILE FORMAT
CREATE OR REPLACE FILE FORMAT SPOTIFY.FILE_FORMATS.csv_file_format
    TYPE = csv
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE;

-- CREATE STORAGE INTEGRATION
CREATE OR REPLACE STORAGE INTEGRATION s3_init
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = '<aws_role_arn>'
    STORAGE_ALLOWED_LOCATIONS = ('s3://<bucket>/')
    COMMENT = 'CREATING CONNECTION TO S3';
DESC INTEGRATION s3_init;

-- CREATE STAGE OBJECT WITH INTEGRATION OBJECT & FILE FORMAT
CREATE OR REPLACE STAGE SPOTIFY.EXTERNAL_STAGES.transformed_folder
    URL = 's3://<bucket>/spotify-data-pipeline/transformed-data/'
    STORAGE_INTEGRATION = s3_init
    FILE_FORMAT = SPOTIFY.FILE_FORMATS.csv_file_format;
LIST @SPOTIFY.EXTERNAL_STAGES.transformed_folder;

-- CREATE PIPES
CREATE OR REPLACE PIPE SPOTIFY.PIPES.album_pipe 
    AUTO_INGEST = TRUE AS
    COPY INTO SPOTIFY.SPOTIFY_TRACK.album
    FROM @SPOTIFY.EXTERNAL_STAGES.transformed_folder/album-data;

CREATE OR REPLACE PIPE SPOTIFY.PIPES.artist_pipe 
    AUTO_INGEST = TRUE AS
    COPY INTO SPOTIFY.SPOTIFY_TRACK.artist
    FROM @SPOTIFY.EXTERNAL_STAGES.transformed_folder/artist-data;

CREATE OR REPLACE PIPE SPOTIFY.PIPES.song_pipe 
    AUTO_INGEST = TRUE AS
    COPY INTO SPOTIFY.SPOTIFY_TRACK.song
    FROM @SPOTIFY.EXTERNAL_STAGES.transformed_folder/song-data;